name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # main branch पर push होने पर चलेगा

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # यहां आपकी HTML/CSS/JS files होनी चाहिए

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages   # ✅ GitHub Pages env का सही नाम
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
